{{- if .Values.assumeRole.create -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8s-ecr-watch.fullname" . }}
data:
  {{- with .Values.configmap.assume_role }}
  assume_role: {{ . }}
  {{- end}}
  {{- with .Values.configmap.credentials }}
  credentials: |-
{{ tpl . $ | indent 4 }}
  {{- end}}
  {{- with .Values.configmap.config }}
  config: |-
{{ tpl . $ | indent 4 }}
  {{- end }}
{{- end}}
